version: '4'
services:
  nginx:
    build:
      context: ./compcs140-nginx-compose
    ports:
      - "8198:8198"
    depends_on:
      - node-app
      - spring-boot-app-1
      - spring-boot-app-2
      - spring-boot-app-3
    networks:
      - app-network


  node-app:
    build:
      context: ./compcs140 nodejs compose
    container_name: node-app
    networks:
      - app-network

  spring-boot-app-1:
    build:
      context: ./compcs140-java-compose
    container_name: java-app-1
    depends_on:
      - node-app
    networks:
      - app-network

  spring-boot-app-2:
    build:
      context: ./compcs140-java-compose
    container_name: java-app-2
    depends_on:
      - node-app
    networks:
      - app-network

  spring-boot-app-3:
    build:
      context: ./compcs140-java-compose
    container_name: java-app-3
    depends_on:
      - node-app
    networks:
      - app-network

  python-shutdown:
    build:
      context: ./compcs140-shutdown-service
    container_name: python-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
networks:
  app-network:
    driver: bridge